In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
b=np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [10]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(type(c))
print(c.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [16]:
#create zeroes, ones, custom array
a=np.zeros((3,3))
print(a)

b=np.ones((2,3))
print(b)

#array of some constant

c=np.full((3,2),5)
print(c)

#IDENTITY MATRIX -SIZE/SQUARE MATRIX
d=np.eye(4)
print(d)
#random matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.24239248 0.62568519 0.66609531]
 [0.73997109 0.56145507 0.43476348]]


In [12]:
print(randomMatrix[:,1])

[0.079486   0.14569993]


In [18]:
randomMatrix[1,1:3]=1
print(randomMatrix)

[[0.40939906 0.50724313 0.08353269]
 [0.65421302 1.         1.        ]]


In [14]:
z=np.zeros((3,3),dtype=np.int64)
print(z)
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [28]:
#Datatypes
print(z.dtype)

int64


In [20]:
#Mathematical Operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

#element wise addition
print(x+y)            #method1
print(np.add(x,y))    #method2

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [21]:
print(x*y)
print(np.multiply(x,y)) #element wise
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [34]:
#Matrix multiplication/ Dot products
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [22]:
#multi of vectors

a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [42]:
a=([1,2,3,4])
print(sum(a))

10


In [53]:
p=np.array([[1,2],[3,4]])
print(np.sum(p))
print(np.sum(p,axis=0))
print(np.sum(p,axis=1))

10
[4 6]
[3 7]


In [23]:
#Stacking of Arrays
a=([1,2,3,4])
print(a)
print(b)
b=b*2
print(b)

[1, 2, 3, 4]
[1 2 3 4]
[2 4 6 8]


In [25]:
np.stack((a,b),axis=0 )

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [26]:
np.stack((a,b),axis=1 )

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [28]:
a=np.array([[1,2,3,4],[4,16,36,64]])
print(a)
a=a.reshape((4,2))
print(a)

[[ 1  2  3  4]
 [ 4 16 36 64]]
[[ 1  2]
 [ 3  4]
 [ 4 16]
 [36 64]]


In [30]:
a=np.reshape((4,-1,3))
print(a)

TypeError: reshape() missing 1 required positional argument: 'newshape'

In [32]:
#RandomModule

a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [17]:
np.random.shuffle(a)
print(a)

[ 9  7 13 12  8 14 10 11  5  6]


In [19]:
a=np.random.rand(2,3)
print(a)

[[0.99208483 0.56484777 0.09200502]
 [0.22472247 0.06700843 0.10238995]]


In [21]:
#returns values from a standard normal distribution
a=np.random.randn(2,3)
print(a)

[[-0.39873295 -0.40484309 -1.89942396]
 [-0.68344464  0.81829969  1.59283502]]


In [23]:
a=np.random.randint(5,10,3)    #prints 3 random int from 5 to 10
print(a)

[9 8 7]


In [26]:
a=np.random.choice([1,4,3,2,11,27])   #prints one random no from the given choices
print(a)

4


In [31]:
#SOME MORE NUMPY FUNCTIONS -STATISTICS

a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))

#Specify axis for the direction i.e axis 0 for along column and axis 1 for rows
print(np.min(a,axis=0)) #finds min element along each column
print(np.min(a,axis=1)) #finds min element along each row

#Mean, average 

b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]
3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [47]:
c=np.array([1,5,4,2,0])
#x=np.sort(c)
#print(x)
print(np.median(c))

#mean vs Average
print(np.mean(c))

w=np.array([1,2,3,4,5])
print(np.average(c,weights=w))

#Stanard dviation

#method1
u=np.mean(c)
myStd=np.sqrt(np.mean(abs(x-u)**2))
print(myStd**2)

#method2
print(np.var(c))


2.0
2.4
2.066666666666667
3.440000000000001
3.4400000000000004
